spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl